spring:
  application:
    name: gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.intance_id:${server.port}}
zuul:
  routes:
    provider-user: /user/**
  retryable: true
